[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ms_seg"
version = "0.0.1"
description = "Multiple Sclerosis lesion segmentation in MRI (Master's thesis, MSLesSeg dataset)"
authors = [
  { name = "Toni" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.11.0"


[tool.ruff]
line-length = 99
src = ["ms_seg"]
include = ["pyproject.toml", "ms_seg/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ms_seg"]
force-sort-within-sections = true

